[package]
name = "google-aip-ordering"
version = "1.0.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
regex = "1.8.4"

[dev-dependencies]
proptest = "1.2.0"
